### ISSUE TITLE
Move logic to xml based parsing.

### ISSUE THREAD

**Issue by iyermuku** [iyers16/bridgetutor.github.io#6]
edit to see better.
<Bid>
<Name>1C</Name>
<Desc>12-21 points; at least 3C</Desc>
<Responses>
<Bid>
<Name>1D</Name>
<Desc> 6-9 points, at least 4D </Desc>
</Bid>
</Responses>
</Bid>
<Bid>
<Name> 1D </Name>
</Bid>
<Bid>
<Name> 1H </Name>
</Bid>
<Bid>
<Name> 1S </Name>
</Bid>

**Comment by iyers16** [comment]
Has been converted to JSON-based parser
